services:

  mysql:
    image: omar0460/employee-management-mysql:latest
    container_name: employee-mysql
    volumes:
      - mysql_data:/var/lib/mysql

  employee-app:
    image: omar0460/employee-management:latest
    container_name: employee-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"

volumes:
  mysql_data: